# Generated by Django 5.0.1 on 2024-04-28 18:33

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("bookMng", "0004_comment"),
    ]

    operations = [
        migrations.RenameField(
            model_name="comment",
            old_name="body",
            new_name="commenter_body",
        ),
    ]
